version: '2'
services:
  declrevenu-app:
    image: declrevenu
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://declrevenu-mysql:3306/declrevenu?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://declrevenu-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://declrevenu-elasticsearch:9200
    ports:
      - 8080:8080
  declrevenu-mysql:
    extends:
      file: mysql.yml
      service: declrevenu-mysql
  declrevenu-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: declrevenu-elasticsearch
